### PR TITLE
OSD-7332: Update for CVEs

### PR DESCRIPTION
**Pull request by lisa**
Signed-off-by: Lisa Seelye <lisa@users.noreply.github.com>

For [OSD-7332](https://issues.redhat.com/browse/OSD-7332)

### CODE REVIEW

**Comment by lisa** [comment]
/hold

This still has a CVE reported by quay.io.

**Comment by jaybeeunix** [comment]
would it be better to switch this from origin-cli to something like ubi? the various ubis tend to be the most up-to-date with cve fixes.

**Review by jaybeeunix — APPROVED** [review]

**Pull request merged**
